### ISSUE TITLE
Movmem patterns in riscv.md

### ISSUE THREAD

**Issue by iz-sc** [riscv/riscv-gcc#85] opened 2017-08-03 19:22 UTC
Hi all!

Sorry if this already was discussed but I haven't managed to find any related discussions.
We've noticed that currently the latest compiler doesn't have momvem patterns which means eg any memcpy is expanded in library call. 
Is this intented for some reasons or it will be added at some moment?

Thanks in advance,
Igor

**Comment by palmer-dabbelt** [comment] 2017-08-03 22:26
https://github.com/riscv/riscv-gcc/pull/67

Some of the tests fail

**Comment by iz-sc** [comment] 2017-08-09 11:26
Ah, sorry, haven't seen this in the issue list with default filters.

Any plans about handling it?

**Comment by palmer-dabbelt** [comment] 2017-08-10 20:09
Sure: the plan is to fix it -- there's just no timeframe on that :).  This manifests as a performance regression in Dhrystone on rv32, so I'll probably get around to it at some point.  Since it's not a correctness issue it's lower priority than getting Linux and glibc upstream, so I don't think it'll happen all that soon.

**Comment by iz-sc** [comment] 2017-08-15 07:12
>  there's just no timeframe on that :). it's lower priority than getting Linux and glibc upstream
Thanks, I see :)

>  This manifests as a performance regression in Dhrystone on rv32
Isn't it a regression on 64 bits also?

Please, just one more question about failing tests - are they performance regression or correctness tests?

**Comment by palmer-dabbelt** [comment] 2017-09-08 21:19
Dhrystone doesn't manifest the performance regression on rv64 in as noticeable of a manner, as with the wider registers GCC will inline longer memcpy instances.

IIRC the failures are correctness related.

**Comment by jim-wilson** [comment] 2018-01-11 22:10
Apparently fixed in November when pull request #67 was merged.

**Closed by jim-wilson** 2018-01-11 22:10 UTC
